<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reflection.proto
#

namespace Crayxn\GrpcServer\Reflection;

use \Crayxn\GrpcServer\ServerContext as Context;

interface ServerReflectionInterface
{
    // grpc service name
    public const SERVICE_NAME = "grpc.reflection.v1alpha.ServerReflection";

	// grpc metadata class
	public const METADATA_CLASS = \Crayxn\GrpcServer\Reflection\GPBMetadata\Reflection::class;

	// grpc dependency file
	public const DEPENDENCY = ["reflection.proto"];

    /**
    * input ServerReflectionRequest
	* output ServerReflectionResponse
    * @param Context $context
    * @return void
    */
    public function ServerReflectionInfo(Context $context): void;

}
